version: 2.1

jobs:
  test:
    docker:
      # the Docker image with Cypress dependencies
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "e2e/package-lock.json" }}
            - v2-deps-{{ .Branch }}-
            - v2-deps-
      - run: npm i
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "e2e/package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache  
      - run:
          name: Running E2E tests
          when: on_success
          command: npm test   
      - store_test_results:
          path: .

workflows:
  build-test:
    jobs:
      - test